# Generated by Django 4.0.1 on 2022-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False, verbose_name='CategoryID')),
                ('category_name', models.CharField(db_column='CategoryName', max_length=30)),
                ('category_type', models.CharField(db_column='Type', max_length=25, null=True)),
                ('color', models.CharField(db_column='Color', default='#FFFFFF', max_length=10)),
                ('description', models.TextField(db_column='Description', max_length=500, null=True)),
            ],
        ),
    ]
