# Generated by Django 4.0.1 on 2022-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, db_column='Type', max_length=25),
        ),
    ]
