# Generated by Django 4.0.1 on 2022-02-01 15:31

import Account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(db_column='AccountID', primary_key=True, serialize=False, verbose_name='AccountID')),
                ('account_name', models.CharField(db_column='AccountName', max_length=30)),
                ('account_type', models.CharField(db_column='AccountType', max_length=25)),
                ('balance', models.DecimalField(db_column='Balance', decimal_places=2, max_digits=100, validators=[Account.models.not_negative])),
            ],
        ),
    ]
