# Generated by Django 4.0.1 on 2022-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(db_column='Type', max_length=25),
        ),
    ]
