# Generated by Django 4.0.1 on 2022-02-02 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mappings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccountmapping',
            options={'verbose_name': 'UserAccountMapping'},
        ),
        migrations.AlterField(
            model_name='useraccountmapping',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
