# Generated by Django 4.0.1 on 2022-02-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_account_type'),
        ('Mappings', '0002_alter_useraccountmapping_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountmapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='useraccountmapping',
            name='account_id',
            field=models.OneToOneField(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.account'),
        ),
    ]
