# Generated by Django 4.0.1 on 2022-02-02 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Transaction', '0005_alter_transaction_description_and_more'),
        ('Budget', '0002_alter_budget_budget_label'),
        ('Account', '0004_alter_account_account_type'),
        ('currency', '0003_alter_currency_type'),
        ('Mappings', '0003_remove_useraccountmapping_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAccountMapping',
            new_name='AccountUserMapping',
        ),
        migrations.AlterModelOptions(
            name='accountusermapping',
            options={'verbose_name': 'AccountUserMapping'},
        ),
        migrations.CreateModel(
            name='TransactionCategoryMapping',
            fields=[
                ('transaction_id', models.OneToOneField(db_column='TransactionID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Transaction.transaction')),
                ('category_id', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
            options={
                'verbose_name': 'TransactionCategoryMapping',
            },
        ),
        migrations.CreateModel(
            name='TransactionAccountMapping',
            fields=[
                ('transaction_id', models.OneToOneField(db_column='TransactionID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Transaction.transaction')),
                ('account_id', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
            options={
                'verbose_name': 'TransactionAccountMapping',
            },
        ),
        migrations.CreateModel(
            name='BudgetAccountMapping',
            fields=[
                ('budget_id', models.OneToOneField(db_column='BudgetID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Budget.budget')),
                ('account_id', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
            options={
                'verbose_name': 'BudgetAccountMapping',
            },
        ),
        migrations.CreateModel(
            name='AccountCurrencyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.OneToOneField(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
                ('currency_id', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.CASCADE, to='currency.currency')),
            ],
            options={
                'verbose_name': 'AccountCurrencyMapping',
            },
        ),
    ]
