# Generated by Django 4.0.1 on 2022-02-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_alter_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mappings', '0004_rename_useraccountmapping_accountusermapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUserMapping',
            fields=[
                ('category_id', models.OneToOneField(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Category.category')),
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CategoryUserMapping',
            },
        ),
        migrations.DeleteModel(
            name='TransactionCategoryMapping',
        ),
    ]
