# Generated by Django 4.0.1 on 2022-02-02 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_account_type'),
        ('Category', '0004_alter_category_description'),
        ('Transaction', '0005_alter_transaction_description_and_more'),
        ('currency', '0003_alter_currency_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mappings', '0005_categoryusermapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategoryAccountMapping',
            fields=[
                ('transaction_id', models.OneToOneField(db_column='TransactionID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Transaction.transaction')),
                ('account_id', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.DO_NOTHING, to='Account.account')),
                ('category_id', models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.DO_NOTHING, to='Category.category')),
            ],
            options={
                'verbose_name': 'TransactionCategoryAccountMapping',
            },
        ),
        migrations.RemoveField(
            model_name='accountcurrencymapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountcurrencymapping',
            name='account_id',
            field=models.OneToOneField(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.account'),
        ),
        migrations.AlterField(
            model_name='accountcurrencymapping',
            name='currency_id',
            field=models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.DO_NOTHING, to='currency.currency'),
        ),
        migrations.AlterField(
            model_name='accountusermapping',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetaccountmapping',
            name='account_id',
            field=models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.DO_NOTHING, to='Account.account'),
        ),
        migrations.AlterField(
            model_name='categoryusermapping',
            name='user_id',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TransactionAccountMapping',
        ),
    ]
