# Generated by Django 4.0.1 on 2022-02-03 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_account_type'),
        ('currency', '0003_alter_currency_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mappings', '0006_transactioncategoryaccountmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUserCurrencyMapping',
            fields=[
                ('account_id', models.OneToOneField(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Account.account')),
                ('currency_id', models.ForeignKey(db_column='CurrencyID', on_delete=django.db.models.deletion.DO_NOTHING, to='currency.currency')),
                ('user_id', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AccountUserCurrencyMapping',
            },
        ),
        migrations.RemoveField(
            model_name='accountusermapping',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='accountusermapping',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='AccountCurrencyMapping',
        ),
        migrations.DeleteModel(
            name='AccountUserMapping',
        ),
    ]
