# Generated by Django 4.0.1 on 2022-02-01 17:26

import Budget.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(db_column='BudgetID', primary_key=True, serialize=False, verbose_name='BudgetID')),
                ('budget_name', models.CharField(db_column='BudgetName', max_length=30)),
                ('budget_label', models.CharField(db_column='BudgetLabel', max_length=30, null=True)),
                ('start_date', models.DateField(db_column='StartDate', default=datetime.date.today)),
                ('end_date', models.DateField(db_column='EndDate')),
                ('budget_amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=100, validators=[Budget.models.not_negative])),
            ],
        ),
    ]
