# Generated by Django 4.0.1 on 2022-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_label',
            field=models.CharField(blank=True, db_column='BudgetLabel', max_length=30),
        ),
    ]
