# Generated by Django 4.0.1 on 2022-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_code',
            field=models.CharField(db_column='Code', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_symbol',
            field=models.CharField(db_column='Symbol', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='type',
            field=models.CharField(choices=[('FIAT', 'Fiat'), ('CRYPTO', 'Crypto')], db_column='Type', max_length=10),
        ),
    ]
