# Generated by Django 4.0.1 on 2022-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='type',
            field=models.CharField(choices=[('FIAT', 'Fiat'), ('CRYPTO', 'Crypto')], db_column='Type', default='FIAT', max_length=10),
        ),
    ]
