# Generated by Django 4.0.1 on 2022-02-01 16:40

import Transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(db_column='TransactionID', primary_key=True, serialize=False, verbose_name='TransactionID')),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], db_column='Type', default='INCOME', max_length=10)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=100, validators=[Transaction.models.not_negative])),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_column='TransactionDate')),
                ('description', models.TextField(db_column='Description', max_length=500, null=True)),
            ],
        ),
    ]
