# Generated by Django 4.0.1 on 2022-02-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(db_column='TransactionDate'),
        ),
    ]
