# Generated by Django 4.0.1 on 2022-02-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_party',
            field=models.CharField(db_column='TransactionParty', max_length=50, null=True),
        ),
    ]
