# Generated by Django 4.0.1 on 2022-02-01 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_transaction_transaction_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(db_column='TransactionDate', default=django.utils.timezone.now),
        ),
    ]
