# Generated by Django 4.0.1 on 2022-02-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0004_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, db_column='Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_party',
            field=models.CharField(blank=True, db_column='TransactionParty', max_length=50),
        ),
    ]
